# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [22]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [23]:
# Import torch
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"
# Create random tensor
torch_a = torch.rand(7,7).to(device)
torch_a

tensor([[0.7749, 0.8208, 0.2793, 0.6817, 0.2837, 0.6567, 0.2388],
        [0.7313, 0.6012, 0.3043, 0.2548, 0.6294, 0.9665, 0.7399],
        [0.4517, 0.4757, 0.7842, 0.1525, 0.6662, 0.3343, 0.7893],
        [0.3216, 0.5247, 0.6688, 0.8436, 0.4265, 0.9561, 0.0770],
        [0.4108, 0.0014, 0.5414, 0.6419, 0.2976, 0.7077, 0.4189],
        [0.0655, 0.8839, 0.8083, 0.7528, 0.8988, 0.6839, 0.7658],
        [0.9149, 0.3993, 0.1100, 0.2541, 0.4333, 0.4451, 0.4966]],
       device='cuda:0')

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [24]:
# Create another random tensor
torch_b = torch.rand(1,7).to(device)

# Perform matrix multiplication 
torch_res = torch.matmul(torch_a, torch_b.T)
torch_res

tensor([[2.1391],
        [2.3548],
        [1.6001],
        [1.9384],
        [1.4356],
        [2.1416],
        [1.7684]], device='cuda:0')

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [25]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor_a = torch.rand(7,7).to(device)
tensor_b = torch.rand(1,7).to(device)

# Matrix multiply tensors
tensor_res = torch.matmul(tensor_a, tensor_b.T)
tensor_res

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]], device='cuda:0')

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [26]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [42]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
print(torch.cuda.is_available())

# Create two random tensors on GPU
tensor_a_gpu = torch.rand(2,3).to("cuda")
tensor_b_gpu = torch.rand(2,3).to("cuda")
tensor_a_gpu, tensor_b_gpu

True


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [28]:
# Perform matmul on tensor_A and tensor_B
tensor_res = torch.matmul(tensor_a_gpu, tensor_b_gpu.T)
tensor_res, tensor_res.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [29]:
# Find max
max_val = torch.max(tensor_res)
print(f"Max value: {max_val}")

# Find min
min_val = torch.min(tensor_res)
print(f"Min value: {min_val}")

Max value: 0.5617256760597229
Min value: 0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [52]:
# Find arg max
torch.manual_seed(123)
tensor_res = torch.rand(3,3,3).to(device)
tensor_flatten = torch.flatten(tensor_res)
print(f"Random tensor: {tensor_res}")
max_val_ind = torch.argmax(tensor_res)
print(max_val_ind)

# Find arg min
min_val_ind = torch.argmin(tensor_res)
print(min_val_ind)

# Accesing the max and min value
print(f"Max value: {tensor_flatten[max_val_ind]}")
print(f"Min value: {tensor_flatten[min_val_ind]}")

Random tensor: tensor([[[0.2961, 0.5166, 0.2517],
         [0.6886, 0.0740, 0.8665],
         [0.1366, 0.1025, 0.1841]],

        [[0.7264, 0.3153, 0.6871],
         [0.0756, 0.1966, 0.3164],
         [0.4017, 0.1186, 0.8274]],

        [[0.3821, 0.6605, 0.8536],
         [0.5932, 0.6367, 0.9826],
         [0.2745, 0.6584, 0.2775]]], device='cuda:0')
tensor(23, device='cuda:0')
tensor(4, device='cuda:0')
Max value: 0.9826293587684631
Min value: 0.07397246360778809



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [54]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_a = torch.rand(1,1,1,10).to(device)

# Remove single dimensions
tensor_squeeze = torch.squeeze(tensor_a)

# Print out tensors and their shapes
tensor_squeeze, tensor_squeeze.shape


(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513], device='cuda:0'),
 torch.Size([10]))